/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SensitivityRouteImport } from './routes/sensitivity'
import { Route as ExplainedRouteImport } from './routes/explained'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AllocatorIndexRouteImport } from './routes/allocator/index'

const SensitivityRoute = SensitivityRouteImport.update({
  id: '/sensitivity',
  path: '/sensitivity',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainedRoute = ExplainedRouteImport.update({
  id: '/explained',
  path: '/explained',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AllocatorIndexRoute = AllocatorIndexRouteImport.update({
  id: '/allocator/',
  path: '/allocator/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explained': typeof ExplainedRoute
  '/sensitivity': typeof SensitivityRoute
  '/allocator/': typeof AllocatorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explained': typeof ExplainedRoute
  '/sensitivity': typeof SensitivityRoute
  '/allocator': typeof AllocatorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explained': typeof ExplainedRoute
  '/sensitivity': typeof SensitivityRoute
  '/allocator/': typeof AllocatorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/explained' | '/sensitivity' | '/allocator/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/explained' | '/sensitivity' | '/allocator'
  id: '__root__' | '/' | '/explained' | '/sensitivity' | '/allocator/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExplainedRoute: typeof ExplainedRoute
  SensitivityRoute: typeof SensitivityRoute
  AllocatorIndexRoute: typeof AllocatorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sensitivity': {
      id: '/sensitivity'
      path: '/sensitivity'
      fullPath: '/sensitivity'
      preLoaderRoute: typeof SensitivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explained': {
      id: '/explained'
      path: '/explained'
      fullPath: '/explained'
      preLoaderRoute: typeof ExplainedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allocator/': {
      id: '/allocator/'
      path: '/allocator'
      fullPath: '/allocator/'
      preLoaderRoute: typeof AllocatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExplainedRoute: ExplainedRoute,
  SensitivityRoute: SensitivityRoute,
  AllocatorIndexRoute: AllocatorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
