/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExplainedRouteImport } from './routes/explained'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SensitivityIndexRouteImport } from './routes/sensitivity/index'
import { Route as MarketDataIndexRouteImport } from './routes/market-data/index'
import { Route as AllocatorIndexRouteImport } from './routes/allocator/index'

const ExplainedRoute = ExplainedRouteImport.update({
  id: '/explained',
  path: '/explained',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SensitivityIndexRoute = SensitivityIndexRouteImport.update({
  id: '/sensitivity/',
  path: '/sensitivity/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketDataIndexRoute = MarketDataIndexRouteImport.update({
  id: '/market-data/',
  path: '/market-data/',
  getParentRoute: () => rootRouteImport,
} as any)
const AllocatorIndexRoute = AllocatorIndexRouteImport.update({
  id: '/allocator/',
  path: '/allocator/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explained': typeof ExplainedRoute
  '/allocator/': typeof AllocatorIndexRoute
  '/market-data/': typeof MarketDataIndexRoute
  '/sensitivity/': typeof SensitivityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explained': typeof ExplainedRoute
  '/allocator': typeof AllocatorIndexRoute
  '/market-data': typeof MarketDataIndexRoute
  '/sensitivity': typeof SensitivityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explained': typeof ExplainedRoute
  '/allocator/': typeof AllocatorIndexRoute
  '/market-data/': typeof MarketDataIndexRoute
  '/sensitivity/': typeof SensitivityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explained'
    | '/allocator/'
    | '/market-data/'
    | '/sensitivity/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/explained' | '/allocator' | '/market-data' | '/sensitivity'
  id:
    | '__root__'
    | '/'
    | '/explained'
    | '/allocator/'
    | '/market-data/'
    | '/sensitivity/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExplainedRoute: typeof ExplainedRoute
  AllocatorIndexRoute: typeof AllocatorIndexRoute
  MarketDataIndexRoute: typeof MarketDataIndexRoute
  SensitivityIndexRoute: typeof SensitivityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/explained': {
      id: '/explained'
      path: '/explained'
      fullPath: '/explained'
      preLoaderRoute: typeof ExplainedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensitivity/': {
      id: '/sensitivity/'
      path: '/sensitivity'
      fullPath: '/sensitivity/'
      preLoaderRoute: typeof SensitivityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-data/': {
      id: '/market-data/'
      path: '/market-data'
      fullPath: '/market-data/'
      preLoaderRoute: typeof MarketDataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allocator/': {
      id: '/allocator/'
      path: '/allocator'
      fullPath: '/allocator/'
      preLoaderRoute: typeof AllocatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExplainedRoute: ExplainedRoute,
  AllocatorIndexRoute: AllocatorIndexRoute,
  MarketDataIndexRoute: MarketDataIndexRoute,
  SensitivityIndexRoute: SensitivityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
