/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SensitivityRouteImport } from './routes/sensitivity'
import { Route as ExplainedRouteImport } from './routes/explained'
import { Route as AllocatorRouteImport } from './routes/allocator'
import { Route as IndexRouteImport } from './routes/index'

const SensitivityRoute = SensitivityRouteImport.update({
  id: '/sensitivity',
  path: '/sensitivity',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainedRoute = ExplainedRouteImport.update({
  id: '/explained',
  path: '/explained',
  getParentRoute: () => rootRouteImport,
} as any)
const AllocatorRoute = AllocatorRouteImport.update({
  id: '/allocator',
  path: '/allocator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/allocator': typeof AllocatorRoute
  '/explained': typeof ExplainedRoute
  '/sensitivity': typeof SensitivityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/allocator': typeof AllocatorRoute
  '/explained': typeof ExplainedRoute
  '/sensitivity': typeof SensitivityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/allocator': typeof AllocatorRoute
  '/explained': typeof ExplainedRoute
  '/sensitivity': typeof SensitivityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/allocator' | '/explained' | '/sensitivity'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/allocator' | '/explained' | '/sensitivity'
  id: '__root__' | '/' | '/allocator' | '/explained' | '/sensitivity'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllocatorRoute: typeof AllocatorRoute
  ExplainedRoute: typeof ExplainedRoute
  SensitivityRoute: typeof SensitivityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sensitivity': {
      id: '/sensitivity'
      path: '/sensitivity'
      fullPath: '/sensitivity'
      preLoaderRoute: typeof SensitivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explained': {
      id: '/explained'
      path: '/explained'
      fullPath: '/explained'
      preLoaderRoute: typeof ExplainedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allocator': {
      id: '/allocator'
      path: '/allocator'
      fullPath: '/allocator'
      preLoaderRoute: typeof AllocatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllocatorRoute: AllocatorRoute,
  ExplainedRoute: ExplainedRoute,
  SensitivityRoute: SensitivityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
